import Head from "next/head";
import { Kanit } from "next/font/google";
import Navbar from "@/components/Navbar";
import SubNavbar from "@/components/SubNavbar";
import Gelery from "@/components/Gelery";
import FloatMenu from "@/components/FloatMenu";
import Footer from "@/components/Footer";
import { ModalProvider } from "@/components/ModalContext";
import { SectionOne } from "@/components/SectionOne";

const kanit = Kanit({ weight: "400", subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>As Deporte</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={kanit.className}>
        <Navbar />
        <ModalProvider>
          <SubNavbar />
          <SectionOne />
          <FloatMenu />
          <Gelery />
          <Footer />
        </ModalProvider>
      </main>
    </>
  );
}
