import Head from "next/head";
import { Kanit } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Navbar from "@/components/Navbar";
import SubNavbar from "@/components/SubNavbar";
import Gelery from "@/components/Gelery";
import FloatMenu from "@/components/FloatMenu";
import Footer from "@/components/Footer";

const kanit = Kanit({ weight: "400", subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>As Deporte</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={kanit.className}>
        <Navbar />
        <SubNavbar />
        <div className={styles.sectionOne}>
          <p className={styles.space}>
            <span>L ´Etape México</span> te lleva a vivir la mejor experiencia
            del Tour de France con el serial de eventos de ciclismo amateur más
            importante en México.
          </p>
          <p>
            Se parte de esta experiencia y rueda en las mejores rutas de México
            diseñadas por expertos del TDF.
          </p>
        </div>
        <FloatMenu />
        <div className={styles.galery}>
          <Gelery />
        </div>
        <Footer />
      </main>
    </>
  );
}
