import Head from "next/head";
import { Kanit } from "next/font/google";
import Navbar from "@/components/Navbar";
import Main from "@/pages/main";

const kanit = Kanit({ weight: "400", subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>As Deporte</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={kanit.className}>
        <Navbar />
        <Main />
      </main>
    </>
  );
}
