export const information = [
  {
    id: "e001",
    image: "/assets/galery/etape.svg",
    title: "L´ETAPE by Tour de France",
    city: "CDMX",
    date: "4 septiembre 2022",
    princeMin: "$680",
    pricePlus: "$580",
  },
  {
    id: "e002",
    image: "/assets/galery/etape.svg",
    title: "L´ETAPE by Tour de France",
    city: "CDMX",
    date: "4 septiembre 2022",
    princeMin: "$680",
    pricePlus: "$580",
  },
  {
    id: "e003",
    image: "/assets/galery/etape.svg",
    title: "L´ETAPE by Tour de France",
    city: "CDMX",
    date: "4 septiembre 2022",
    princeMin: "$680",
    pricePlus: "$580",
  },
  {
    id: "e004",
    image: "/assets/galery/etape.svg",
    title: "L´ETAPE by Tour de France",
    city: "CDMX",
    date: "4 septiembre 2022",
    princeMin: "$680",
    pricePlus: "$580",
  },
  {
    id: "e005",
    image: "/assets/galery/etape.svg",
    title: "L´ETAPE by Tour de France",
    city: "CDMX",
    date: "4 septiembre 2022",
    princeMin: "$680",
    pricePlus: "$580",
  },
  {
    id: "e006",
    image: "/assets/galery/etape.svg",
    title: "L´ETAPE by Tour de France",
    city: "CDMX",
    date: "4 septiembre 2022",
    princeMin: "$680",
    pricePlus: "$580",
  },
];
